
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programmeNUMBER ID OPBIN LPAREN RPAREN LACO RACO END AFFECT COMMA FINISH MAIN IF RETURN WHILE PRINTprogramme : MAIN LPAREN enum RPAREN LACO commande FINISH PRINT LPAREN expression RPAREN RACO\n    enum : ID\n              | ID COMMA enum\n    empty :commande : ID AFFECT expression\n                  | commande END commande\n                  | WHILE LPAREN expression RPAREN LACO commande RACOexpression :  NUMBER\n                    | ID\n                    | expression OPBIN expression'
    
_lr_action_items = {'COMMA':([5,],[7,]),'LPAREN':([1,11,18,],[3,15,23,]),'OPBIN':([19,20,21,22,26,28,],[-8,25,-9,25,25,25,]),'FINISH':([10,17,19,21,22,28,32,],[14,-6,-8,-9,-5,-10,-7,]),'LACO':([6,24,],[8,27,]),'END':([10,17,19,21,22,28,30,32,],[13,13,-8,-9,-5,-10,13,-7,]),'WHILE':([8,13,27,],[11,11,11,]),'RPAREN':([4,5,9,19,20,21,26,28,],[6,-2,-3,-8,24,-9,29,-10,]),'NUMBER':([15,16,23,25,],[19,19,19,19,]),'AFFECT':([12,],[16,]),'ID':([3,7,8,13,15,16,23,25,27,],[5,5,12,12,21,21,21,21,12,]),'$end':([2,31,],[0,-1,]),'PRINT':([14,],[18,]),'MAIN':([0,],[1,]),'RACO':([17,19,21,22,28,29,30,32,],[-6,-8,-9,-5,-10,31,32,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([15,16,23,25,],[20,22,26,28,]),'programme':([0,],[2,]),'commande':([8,13,27,],[10,17,30,]),'enum':([3,7,],[4,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programme","S'",1,None,None,None),
  ('programme -> MAIN LPAREN enum RPAREN LACO commande FINISH PRINT LPAREN expression RPAREN RACO','programme',12,'p_programme','compilateur.py',83),
  ('enum -> ID','enum',1,'p_enum','compilateur.py',92),
  ('enum -> ID COMMA enum','enum',3,'p_enum','compilateur.py',93),
  ('empty -> <empty>','empty',0,'p_empty','compilateur.py',102),
  ('commande -> ID AFFECT expression','commande',3,'p_commande','compilateur.py',105),
  ('commande -> commande END commande','commande',3,'p_commande','compilateur.py',106),
  ('commande -> WHILE LPAREN expression RPAREN LACO commande RACO','commande',7,'p_commande','compilateur.py',107),
  ('expression -> NUMBER','expression',1,'p_expression','compilateur.py',123),
  ('expression -> ID','expression',1,'p_expression','compilateur.py',124),
  ('expression -> expression OPBIN expression','expression',3,'p_expression','compilateur.py',125),
]
