
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programmeNUMBER ID OPBIN LPAREN RPAREN LACO RACO END AFFECT COMMA FINISH IF RETURN PRINT MAIN WHILEprogramme : MAIN LPAREN enum RPAREN LACO commande FINISH PRINT LPAREN expression RPAREN RACO\n    enum : ID\n              | ID COMMA enum\n    empty :commande : ID AFFECT expression\n                  | commande END commande\n                  | WHILE LPAREN expression RPAREN LACO commande RACOexpression :  NUMBER\n                    | ID\n                    | expression OPBIN expression'
    
_lr_action_items = {'RACO':([17,18,19,21,26,29,30,32,],[-8,-9,-5,-6,-10,31,32,-7,]),'RPAREN':([4,5,8,17,18,22,26,27,],[-2,7,-3,-8,-9,25,-10,29,]),'LPAREN':([1,12,20,],[3,16,24,]),'COMMA':([4,],[6,]),'NUMBER':([13,16,23,24,],[17,17,17,17,]),'END':([11,17,18,19,21,26,30,32,],[15,-8,-9,-5,15,-10,15,-7,]),'ID':([3,6,9,13,15,16,23,24,28,],[4,4,10,18,10,18,18,18,10,]),'AFFECT':([10,],[13,]),'OPBIN':([17,18,19,22,26,27,],[-8,-9,23,23,23,23,]),'$end':([2,31,],[0,-1,]),'LACO':([7,25,],[9,28,]),'FINISH':([11,17,18,19,21,26,32,],[14,-8,-9,-5,-6,-10,-7,]),'WHILE':([9,15,28,],[12,12,12,]),'PRINT':([14,],[20,]),'MAIN':([0,],[1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([13,16,23,24,],[19,22,26,27,]),'enum':([3,6,],[5,8,]),'commande':([9,15,28,],[11,21,30,]),'programme':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programme","S'",1,None,None,None),
  ('programme -> MAIN LPAREN enum RPAREN LACO commande FINISH PRINT LPAREN expression RPAREN RACO','programme',12,'p_programme','compilateur.py',83),
  ('enum -> ID','enum',1,'p_enum','compilateur.py',92),
  ('enum -> ID COMMA enum','enum',3,'p_enum','compilateur.py',93),
  ('empty -> <empty>','empty',0,'p_empty','compilateur.py',102),
  ('commande -> ID AFFECT expression','commande',3,'p_commande','compilateur.py',105),
  ('commande -> commande END commande','commande',3,'p_commande','compilateur.py',106),
  ('commande -> WHILE LPAREN expression RPAREN LACO commande RACO','commande',7,'p_commande','compilateur.py',107),
  ('expression -> NUMBER','expression',1,'p_expression','compilateur.py',123),
  ('expression -> ID','expression',1,'p_expression','compilateur.py',124),
  ('expression -> expression OPBIN expression','expression',3,'p_expression','compilateur.py',125),
]
