
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programmeNUMBER ID OPBIN LPAREN RPAREN LACO RACO END AFFECT COMMA FINISH IF WHILE RETURN PRINT MAINprogramme : MAIN LPAREN enum RPAREN LACO commande FINISH PRINT LPAREN expression RPAREN RACO\n    enum : ID\n              | ID COMMA enum\n    empty :commande : ID AFFECT expression\n                  | commande END commande\n                  | WHILE LPAREN expression RPAREN LACO commande RACOexpression :  NUMBER\n                    | ID\n                    | expression OPBIN expression'
    
_lr_action_items = {'WHILE':([8,14,26,],[10,10,10,]),'MAIN':([0,],[1,]),'END':([11,17,19,20,22,27,29,31,],[14,-8,-9,14,-5,-10,14,-7,]),'COMMA':([5,],[7,]),'LACO':([6,23,],[8,26,]),'RACO':([17,19,20,22,27,29,30,31,],[-8,-9,-6,-5,-10,31,32,-7,]),'LPAREN':([1,10,21,],[3,13,25,]),'NUMBER':([13,16,24,25,],[17,17,17,17,]),'RPAREN':([4,5,9,17,18,19,27,28,],[6,-2,-3,-8,23,-9,-10,30,]),'AFFECT':([12,],[16,]),'ID':([3,7,8,13,14,16,24,25,26,],[5,5,12,19,12,19,19,19,12,]),'OPBIN':([17,18,19,22,27,28,],[-8,24,-9,24,24,24,]),'PRINT':([15,],[21,]),'$end':([2,32,],[0,-1,]),'FINISH':([11,17,19,20,22,27,31,],[15,-8,-9,-6,-5,-10,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'enum':([3,7,],[4,9,]),'expression':([13,16,24,25,],[18,22,27,28,]),'commande':([8,14,26,],[11,20,29,]),'programme':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programme","S'",1,None,None,None),
  ('programme -> MAIN LPAREN enum RPAREN LACO commande FINISH PRINT LPAREN expression RPAREN RACO','programme',12,'p_programme','compilateur.py',84),
  ('enum -> ID','enum',1,'p_enum','compilateur.py',93),
  ('enum -> ID COMMA enum','enum',3,'p_enum','compilateur.py',94),
  ('empty -> <empty>','empty',0,'p_empty','compilateur.py',103),
  ('commande -> ID AFFECT expression','commande',3,'p_commande','compilateur.py',106),
  ('commande -> commande END commande','commande',3,'p_commande','compilateur.py',107),
  ('commande -> WHILE LPAREN expression RPAREN LACO commande RACO','commande',7,'p_commande','compilateur.py',108),
  ('expression -> NUMBER','expression',1,'p_expression','compilateur.py',124),
  ('expression -> ID','expression',1,'p_expression','compilateur.py',125),
  ('expression -> expression OPBIN expression','expression',3,'p_expression','compilateur.py',126),
]
